POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": "180"
}

###

GET http://localhost:3333/videos

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/b025c3cc-07bf-4392-8141-6103342a7124
Content-type: application/json

{
    "title": "Video 2",
    "description": "Esse é o primeiro video",
    "duration": "180"
}

###

DELETE http://localhost:3333/videos/d36cbe98-b53d-4fd4-9936-7dc5b37a0250